### ISSUE TITLE
Add AdiIRC support

### ISSUE THREAD

**Issue by tbs** [Membear/mToast#2]
The title is my suggestion.

More info:

https://adiirc.com/

https://dev.adiirc.com/

**Comment by westor7** [comment]
That would be very good, but AdiIRC has 32 + 64 bits support so need to change a lot...

**Comment by westor7** [comment]
AdiiRC has added that by default, also exist an option to enable/disable it. FUCK YES!

https://dev.adiirc.com/issues/4123
